name: "Build the extension"
on:
  pull_request:
    # Only the following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096 --trace-warnings"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 24.x
        uses: actions/upload-artifact@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the extension
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Archive the extension production build as ZIP
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.sha }}-prod-build
          path: build/chrome-mv3-prod.zip
          retention-days: 30
